import java.util.Scanner;

public class Exception_Handling_81 {
    public static void main(String[] args) {
        int[] arr = new int[5];
        arr[0] = 4;
        arr[1] = 8;
        arr[2] = 9;
        arr[3] = 2;
        arr[4] = 5;
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the index of element to be accessed:");
        int n = sc.nextInt();

        System.out.println("The number you want to divide: ");
        int number = sc.nextInt();
        try {
            System.out.println("The value at array index endered is: " + arr[n]);
            System.out.println("The value of array-value/number is: " + arr[n] / number);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Error! Index is out of bound.");
            System.out.println(e);
        } catch (ArithmeticException e2) {
            System.out.println("Error! Division by zero not allowed.");
            System.out.println(e2);
        } catch (NumberFormatException e3) {
            System.out.println("Error! Please enter a valid integer input for division.");
            System.out.println(e3);
        } catch (Exception e4) {
            System.out.println("An error occurred while performing operations.");
            System.out.println(e4);
        }

    }
}

// finish.
